
# Load bashrc
[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

# Ruby Version Manager
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Node Version Manager
[[ -s "$HOME/.nvm/nvm.sh" ]] && source "$HOME/.nvm/nvm.sh"
unset NVM_NODEJS_ORG_MIRROR
unset NVM_IOJS_ORG_MIRROR
export NVM_NODEJS_ORG_MIRROR=http://nodejs.org/dist

# Elixir Version Manager
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"
eval "$(/opt/homebrew/bin/brew shellenv)"
