
# Load bashrc
[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

export NVM_DIR=~/.nvm
. $(brew --prefix nvm)/nvm.sh
